//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrthopedicClinic
{
    using System;
    using System.Collections.Generic;
    
    public partial class KindOfProcedures
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KindOfProcedures()
        {
            this.Procedures = new HashSet<Procedures>();
            this.TypeOfProcedures1 = new HashSet<TypeOfProcedures>();
        }
    
        public int Id { get; set; }
        public string Description { get; set; }
        public string Name { get; set; }
        public Nullable<int> TypeOfProcedure_ID { get; set; }
        public Nullable<System.DateTime> DeleteTime { get; set; }
    
        public virtual TypeOfProcedures TypeOfProcedures { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Procedures> Procedures { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TypeOfProcedures> TypeOfProcedures1 { get; set; }
    }
}
