//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrthopedicClinic
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pays
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> Patient_ID { get; set; }
        public Nullable<int> Procedure_ID { get; set; }
        public Nullable<int> Worker_ID { get; set; }
        public Nullable<int> Status { get; set; }
    
        public virtual Patients Patients { get; set; }
        public virtual Workers Workers { get; set; }
        public virtual Procedures Procedures { get; set; }
    }
}
