//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrthopedicClinic
{
    using System;
    using System.Collections.Generic;
    
    public partial class Procedures
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Procedures()
        {
            this.DiagnosisesProcedures = new HashSet<DiagnosisesProcedures>();
            this.FilesProcedures = new HashSet<FilesProcedures>();
            this.Pays = new HashSet<Pays>();
            this.TreatmentPlanProcedures = new HashSet<TreatmentPlanProcedures>();
            this.VisitProcedures = new HashSet<VisitProcedures>();
        }
    
        public int Id { get; set; }
        public Nullable<System.DateTime> DateFact { get; set; }
        public Nullable<System.DateTime> DateEventStart { get; set; }
        public string Description { get; set; }
        public Nullable<int> KindOfProcedure_ID { get; set; }
        public Nullable<int> TypeOfProcedure_ID { get; set; }
        public Nullable<System.DateTime> DeleteTime { get; set; }
        public Nullable<int> Patient_ID { get; set; }
        public Nullable<int> Worker_ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> Cabinet_ID { get; set; }
        public Nullable<int> IsOurs { get; set; }
        public Nullable<System.DateTime> DateEventEnd { get; set; }
    
        public virtual Cabinets Cabinets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DiagnosisesProcedures> DiagnosisesProcedures { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FilesProcedures> FilesProcedures { get; set; }
        public virtual KindOfProcedures KindOfProcedures { get; set; }
        public virtual Patients Patients { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pays> Pays { get; set; }
        public virtual Workers Workers { get; set; }
        public virtual TypeOfProcedures TypeOfProcedures { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TreatmentPlanProcedures> TreatmentPlanProcedures { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VisitProcedures> VisitProcedures { get; set; }
    }
}
