//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrthopedicClinic
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkerWorkingHours
    {
        public int Worker_ID { get; set; }
        public int WorkingHour_ID { get; set; }
        public Nullable<System.DateTime> DeleteTime { get; set; }
    
        public virtual Workers Workers { get; set; }
        public virtual WorkingHours WorkingHours { get; set; }
    }
}
